version: '3.7'

#
# This version runs in production mode and tries to recycle HTTPS certificates.
#

#networks:
#  proxy_net:
#    name: proxy_net
#    external: true

volumes:
  certs:
    name: proxy_certs    
    external: true

services:
  svelte:
    container_name: svelte-template
    image: svelte-template
    build:
      context: .
      dockerfile: Dockerfile.test_front_end
      args:
        - FQDN=${FQDN}
    environment:
      NODE_ENV: production
    ports:
      - "10443:10443"
    volumes:
      - ${PWD}/auth_config.ts:/home/node/auth_config.ts:rw
      - ${PWD}/front_end:/home/node/src:rw
      - certs:/srv/certs:ro

#    networks:
#      proxy_net:
#        ipv4_address: ${STATIC_IP_ADDRESS}
