# NB, we need Python3 for node building
FROM node:current-bullseye

# This is only needed to build node packages, not in production.
RUN apt-get update && \
    apt-get install -y build-essential

RUN adduser svelte
USER svelte

RUN npm install parcel -g

ARG FQDN
ENV FQDN ${FQDN}

ARG LOCN
ENV LOCN ${LOCN}

WORKDIR /srv
COPY start_front_end.sh /srv
