version: '3.7'
#networks:
#  proxy_net:
#    name: proxy_net
#    external: true

volumes:
  certs:
    name: caddy_data    
    external: true

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.test_front_end
      args:
        - FQDN=${FQDN}
        - LOCN=${LOCN}
    ports:
      - "10443:10443"
    volumes:
      - ./front_end:/srv/app:rw
      - certs:/srv/certs:ro
    command: ['/srv/start_front_end.sh']
#    networks:
#      proxy_net:
#        ipv4_address: ${STATIC_IP_ADDRESS}
